pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            url = 'https://maven.parchmentmc.org'
        }
        maven {
            url = 'https://repo.spongepowered.org/maven'
        }
        maven {
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
        mavenCentral()
    }
}